// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package restapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for TektonResultSummaryStatus.
const (
	CANCELLED TektonResultSummaryStatus = "CANCELLED"
	FAILURE   TektonResultSummaryStatus = "FAILURE"
	SUCCESS   TektonResultSummaryStatus = "SUCCESS"
	TIMEOUT   TektonResultSummaryStatus = "TIMEOUT"
	UNKNOWN   TektonResultSummaryStatus = "UNKNOWN"
)

// PipelineRunResultsResponse defines model for PipelineRunResultsResponse.
type PipelineRunResultsResponse struct {
	NextPageToken *string        `json:"nextPageToken,omitempty"`
	Results       []TektonResult `json:"results"`
}

// StepTerminated defines model for StepTerminated.
type StepTerminated struct {
	ContainerID *string `json:"containerID,omitempty"`
	ExitCode    int     `json:"exitCode"`
	FinishedAt  *string `json:"finishedAt,omitempty"`
	Message     *string `json:"message,omitempty"`
	Reason      *string `json:"reason,omitempty"`
	Signal      *int    `json:"signal,omitempty"`
	StartedAt   *string `json:"startedAt,omitempty"`
}

// TaskRun defines model for TaskRun.
type TaskRun struct {
	ApiVersion string          `json:"apiVersion"`
	Kind       string          `json:"kind"`
	Metadata   TaskRunMetadata `json:"metadata"`
	Spec       struct {
		Params *[]struct {
			Name  string       `json:"name"`
			Value *interface{} `json:"value,omitempty"`
		} `json:"params,omitempty"`
		ServiceAccountName *string `json:"serviceAccountName,omitempty"`
		TaskRef            *struct {
			ApiVersion *string `json:"apiVersion,omitempty"`
			Kind       *string `json:"kind,omitempty"`
			Name       *string `json:"name,omitempty"`
			Resolver   *string `json:"resolver,omitempty"`
		} `json:"taskRef,omitempty"`
		Timeout    *string                   `json:"timeout,omitempty"`
		Workspaces *[]map[string]interface{} `json:"workspaces,omitempty"`
	} `json:"spec"`
	Status TaskRunStatus `json:"status"`
}

// TaskRunCondition defines model for TaskRunCondition.
type TaskRunCondition struct {
	LastTransitionTime *string `json:"lastTransitionTime,omitempty"`
	Message            *string `json:"message,omitempty"`
	Reason             *string `json:"reason,omitempty"`
	Status             string  `json:"status"`
	Type               string  `json:"type"`
}

// TaskRunMetadata defines model for TaskRunMetadata.
type TaskRunMetadata struct {
	Annotations       *map[string]string `json:"annotations,omitempty"`
	CreationTimestamp *string            `json:"creationTimestamp,omitempty"`
	Generation        *int               `json:"generation,omitempty"`
	Labels            *map[string]string `json:"labels,omitempty"`
	Name              string             `json:"name"`
	Namespace         string             `json:"namespace"`
	ResourceVersion   *string            `json:"resourceVersion,omitempty"`
	Uid               string             `json:"uid"`
}

// TaskRunRecordsResponse defines model for TaskRunRecordsResponse.
type TaskRunRecordsResponse struct {
	TaskRuns []TaskRun `json:"taskRuns"`
}

// TaskRunStatus defines model for TaskRunStatus.
type TaskRunStatus struct {
	Annotations    *map[string]string  `json:"annotations,omitempty"`
	CompletionTime *string             `json:"completionTime,omitempty"`
	Conditions     *[]TaskRunCondition `json:"conditions,omitempty"`
	PodName        string              `json:"podName"`
	Results        *[]struct {
		Name  string       `json:"name"`
		Type  *string      `json:"type,omitempty"`
		Value *interface{} `json:"value,omitempty"`
	} `json:"results,omitempty"`
	Sidecars    *[]interface{}     `json:"sidecars,omitempty"`
	SpanContext *map[string]string `json:"spanContext,omitempty"`
	StartTime   *string            `json:"startTime,omitempty"`
	Steps       *[]TaskRunStep     `json:"steps,omitempty"`
	TaskResults *[]struct {
		Name  string       `json:"name"`
		Type  *string      `json:"type,omitempty"`
		Value *interface{} `json:"value,omitempty"`
	} `json:"taskResults,omitempty"`
	TaskSpec *interface{} `json:"taskSpec,omitempty"`
}

// TaskRunStep defines model for TaskRunStep.
type TaskRunStep struct {
	Container *string `json:"container,omitempty"`
	ImageID   *string `json:"imageID,omitempty"`
	Name      *string `json:"name,omitempty"`
	Results   *[]struct {
		Name  string       `json:"name"`
		Type  *string      `json:"type,omitempty"`
		Value *interface{} `json:"value,omitempty"`
	} `json:"results,omitempty"`
	Running *struct {
		StartedAt *string `json:"startedAt,omitempty"`
	} `json:"running,omitempty"`
	Terminated *StepTerminated `json:"terminated,omitempty"`
	Waiting    *struct {
		Message *string `json:"message,omitempty"`
		Reason  *string `json:"reason,omitempty"`
	} `json:"waiting,omitempty"`
}

// TektonResult defines model for TektonResult.
type TektonResult struct {
	Annotations *map[string]interface{} `json:"annotations,omitempty"`
	CreateTime  string                  `json:"create_time"`
	Etag        *string                 `json:"etag,omitempty"`
	Name        string                  `json:"name"`
	Summary     *TektonResultSummary    `json:"summary,omitempty"`
	Uid         string                  `json:"uid"`
	UpdateTime  string                  `json:"update_time"`
}

// TektonResultSummary defines model for TektonResultSummary.
type TektonResultSummary struct {
	Annotations *map[string]interface{}   `json:"annotations,omitempty"`
	EndTime     *string                   `json:"end_time,omitempty"`
	Record      string                    `json:"record"`
	StartTime   *string                   `json:"start_time,omitempty"`
	Status      TektonResultSummaryStatus `json:"status"`
	Type        string                    `json:"type"`
}

// TektonResultSummaryStatus defines model for TektonResultSummary.Status.
type TektonResultSummaryStatus string

// ErrorBADREQUEST The error information
type ErrorBADREQUEST struct {
	// Code The error code
	Code string `json:"code"`

	// Issues An array of issues that were responsible for the error
	Issues *[]struct {
		Message string `json:"message"`
	} `json:"issues,omitempty"`

	// Message The error message
	Message string `json:"message"`
}

// ErrorFORBIDDEN The error information
type ErrorFORBIDDEN struct {
	// Code The error code
	Code string `json:"code"`

	// Issues An array of issues that were responsible for the error
	Issues *[]struct {
		Message string `json:"message"`
	} `json:"issues,omitempty"`

	// Message The error message
	Message string `json:"message"`
}

// ErrorINTERNALSERVERERROR The error information
type ErrorINTERNALSERVERERROR struct {
	// Code The error code
	Code string `json:"code"`

	// Issues An array of issues that were responsible for the error
	Issues *[]struct {
		Message string `json:"message"`
	} `json:"issues,omitempty"`

	// Message The error message
	Message string `json:"message"`
}

// ErrorNOTFOUND The error information
type ErrorNOTFOUND struct {
	// Code The error code
	Code string `json:"code"`

	// Issues An array of issues that were responsible for the error
	Issues *[]struct {
		Message string `json:"message"`
	} `json:"issues,omitempty"`

	// Message The error message
	Message string `json:"message"`
}

// ErrorUNAUTHORIZED The error information
type ErrorUNAUTHORIZED struct {
	// Code The error code
	Code string `json:"code"`

	// Issues An array of issues that were responsible for the error
	Issues *[]struct {
		Message string `json:"message"`
	} `json:"issues,omitempty"`

	// Message The error message
	Message string `json:"message"`
}

// TektonResultsGetPipelineRunResultsParams defines parameters for TektonResultsGetPipelineRunResults.
type TektonResultsGetPipelineRunResultsParams struct {
	Namespace string   `form:"namespace" json:"namespace"`
	PageSize  *float32 `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PageToken *string  `form:"pageToken,omitempty" json:"pageToken,omitempty"`
	Filter    *string  `form:"filter,omitempty" json:"filter,omitempty"`
}

// TektonResultsGetPipelineRunLogsParams defines parameters for TektonResultsGetPipelineRunLogs.
type TektonResultsGetPipelineRunLogsParams struct {
	Namespace string             `form:"namespace" json:"namespace"`
	RecordUid openapi_types.UUID `form:"recordUid" json:"recordUid"`
}

// TektonResultsGetTaskRunRecordsParams defines parameters for TektonResultsGetTaskRunRecords.
type TektonResultsGetTaskRunRecordsParams struct {
	Namespace string `form:"namespace" json:"namespace"`
}

// K8sGetJSONBody defines parameters for K8sGet.
type K8sGetJSONBody struct {
	ClusterName    string  `json:"clusterName"`
	Name           string  `json:"name"`
	Namespace      *string `json:"namespace,omitempty"`
	ResourceConfig struct {
		ApiVersion    string             `json:"apiVersion"`
		ClusterScoped *bool              `json:"clusterScoped,omitempty"`
		Group         string             `json:"group"`
		Kind          string             `json:"kind"`
		Labels        *map[string]string `json:"labels,omitempty"`
		PluralName    string             `json:"pluralName"`
		SingularName  string             `json:"singularName"`
		Version       string             `json:"version"`
	} `json:"resourceConfig"`
}

// K8sListJSONBody defines parameters for K8sList.
type K8sListJSONBody struct {
	ClusterName    string             `json:"clusterName"`
	Labels         *map[string]string `json:"labels,omitempty"`
	Namespace      *string            `json:"namespace,omitempty"`
	ResourceConfig struct {
		ApiVersion    string             `json:"apiVersion"`
		ClusterScoped *bool              `json:"clusterScoped,omitempty"`
		Group         string             `json:"group"`
		Kind          string             `json:"kind"`
		Labels        *map[string]string `json:"labels,omitempty"`
		PluralName    string             `json:"pluralName"`
		SingularName  string             `json:"singularName"`
		Version       string             `json:"version"`
	} `json:"resourceConfig"`
}

// TektonResultsGetTaskRunLogsParams defines parameters for TektonResultsGetTaskRunLogs.
type TektonResultsGetTaskRunLogsParams struct {
	Namespace   string  `form:"namespace" json:"namespace"`
	TaskRunName string  `form:"taskRunName" json:"taskRunName"`
	StepName    *string `form:"stepName,omitempty" json:"stepName,omitempty"`
}

// K8sGetJSONRequestBody defines body for K8sGet for application/json ContentType.
type K8sGetJSONRequestBody K8sGetJSONBody

// K8sListJSONRequestBody defines body for K8sList for application/json ContentType.
type K8sListJSONRequestBody K8sListJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ConfigGet request
	ConfigGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConfigOidc request
	ConfigOidc(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TektonResultsGetPipelineRunResults request
	TektonResultsGetPipelineRunResults(ctx context.Context, params *TektonResultsGetPipelineRunResultsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TektonResultsGetPipelineRunLogs request
	TektonResultsGetPipelineRunLogs(ctx context.Context, resultUid openapi_types.UUID, params *TektonResultsGetPipelineRunLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TektonResultsGetTaskRunRecords request
	TektonResultsGetTaskRunRecords(ctx context.Context, resultUid openapi_types.UUID, params *TektonResultsGetTaskRunRecordsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// K8sGetWithBody request with any body
	K8sGetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	K8sGet(ctx context.Context, body K8sGetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// K8sListWithBody request with any body
	K8sListWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	K8sList(ctx context.Context, body K8sListJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TektonResultsGetTaskRunLogs request
	TektonResultsGetTaskRunLogs(ctx context.Context, resultUid openapi_types.UUID, params *TektonResultsGetTaskRunLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ConfigGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConfigGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConfigOidc(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConfigOidcRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TektonResultsGetPipelineRunResults(ctx context.Context, params *TektonResultsGetPipelineRunResultsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTektonResultsGetPipelineRunResultsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TektonResultsGetPipelineRunLogs(ctx context.Context, resultUid openapi_types.UUID, params *TektonResultsGetPipelineRunLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTektonResultsGetPipelineRunLogsRequest(c.Server, resultUid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TektonResultsGetTaskRunRecords(ctx context.Context, resultUid openapi_types.UUID, params *TektonResultsGetTaskRunRecordsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTektonResultsGetTaskRunRecordsRequest(c.Server, resultUid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) K8sGetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewK8sGetRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) K8sGet(ctx context.Context, body K8sGetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewK8sGetRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) K8sListWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewK8sListRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) K8sList(ctx context.Context, body K8sListJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewK8sListRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TektonResultsGetTaskRunLogs(ctx context.Context, resultUid openapi_types.UUID, params *TektonResultsGetTaskRunLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTektonResultsGetTaskRunLogsRequest(c.Server, resultUid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewConfigGetRequest generates requests for ConfigGet
func NewConfigGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/config")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewConfigOidcRequest generates requests for ConfigOidc
func NewConfigOidcRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/config/oidc")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTektonResultsGetPipelineRunResultsRequest generates requests for TektonResultsGetPipelineRunResults
func NewTektonResultsGetPipelineRunResultsRequest(server string, params *TektonResultsGetPipelineRunResultsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/pipeline-runs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "namespace", runtime.ParamLocationQuery, params.Namespace); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "pageSize", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "pageToken", runtime.ParamLocationQuery, *params.PageToken); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Filter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "filter", runtime.ParamLocationQuery, *params.Filter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTektonResultsGetPipelineRunLogsRequest generates requests for TektonResultsGetPipelineRunLogs
func NewTektonResultsGetPipelineRunLogsRequest(server string, resultUid openapi_types.UUID, params *TektonResultsGetPipelineRunLogsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "resultUid", runtime.ParamLocationPath, resultUid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/pipeline-runs/%s/logs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "namespace", runtime.ParamLocationQuery, params.Namespace); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "recordUid", runtime.ParamLocationQuery, params.RecordUid); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTektonResultsGetTaskRunRecordsRequest generates requests for TektonResultsGetTaskRunRecords
func NewTektonResultsGetTaskRunRecordsRequest(server string, resultUid openapi_types.UUID, params *TektonResultsGetTaskRunRecordsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "resultUid", runtime.ParamLocationPath, resultUid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/pipeline-runs/%s/task-runs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "namespace", runtime.ParamLocationQuery, params.Namespace); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewK8sGetRequest calls the generic K8sGet builder with application/json body
func NewK8sGetRequest(server string, body K8sGetJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewK8sGetRequestWithBody(server, "application/json", bodyReader)
}

// NewK8sGetRequestWithBody generates requests for K8sGet with any type of body
func NewK8sGetRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/resources/get")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewK8sListRequest calls the generic K8sList builder with application/json body
func NewK8sListRequest(server string, body K8sListJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewK8sListRequestWithBody(server, "application/json", bodyReader)
}

// NewK8sListRequestWithBody generates requests for K8sList with any type of body
func NewK8sListRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/resources/list")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTektonResultsGetTaskRunLogsRequest generates requests for TektonResultsGetTaskRunLogs
func NewTektonResultsGetTaskRunLogsRequest(server string, resultUid openapi_types.UUID, params *TektonResultsGetTaskRunLogsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "resultUid", runtime.ParamLocationPath, resultUid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/task-runs/%s/logs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "namespace", runtime.ParamLocationQuery, params.Namespace); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "taskRunName", runtime.ParamLocationQuery, params.TaskRunName); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.StepName != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "stepName", runtime.ParamLocationQuery, *params.StepName); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ConfigGetWithResponse request
	ConfigGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ConfigGetResponse, error)

	// ConfigOidcWithResponse request
	ConfigOidcWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ConfigOidcResponse, error)

	// TektonResultsGetPipelineRunResultsWithResponse request
	TektonResultsGetPipelineRunResultsWithResponse(ctx context.Context, params *TektonResultsGetPipelineRunResultsParams, reqEditors ...RequestEditorFn) (*TektonResultsGetPipelineRunResultsResponse, error)

	// TektonResultsGetPipelineRunLogsWithResponse request
	TektonResultsGetPipelineRunLogsWithResponse(ctx context.Context, resultUid openapi_types.UUID, params *TektonResultsGetPipelineRunLogsParams, reqEditors ...RequestEditorFn) (*TektonResultsGetPipelineRunLogsResponse, error)

	// TektonResultsGetTaskRunRecordsWithResponse request
	TektonResultsGetTaskRunRecordsWithResponse(ctx context.Context, resultUid openapi_types.UUID, params *TektonResultsGetTaskRunRecordsParams, reqEditors ...RequestEditorFn) (*TektonResultsGetTaskRunRecordsResponse, error)

	// K8sGetWithBodyWithResponse request with any body
	K8sGetWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*K8sGetResponse, error)

	K8sGetWithResponse(ctx context.Context, body K8sGetJSONRequestBody, reqEditors ...RequestEditorFn) (*K8sGetResponse, error)

	// K8sListWithBodyWithResponse request with any body
	K8sListWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*K8sListResponse, error)

	K8sListWithResponse(ctx context.Context, body K8sListJSONRequestBody, reqEditors ...RequestEditorFn) (*K8sListResponse, error)

	// TektonResultsGetTaskRunLogsWithResponse request
	TektonResultsGetTaskRunLogsWithResponse(ctx context.Context, resultUid openapi_types.UUID, params *TektonResultsGetTaskRunLogsParams, reqEditors ...RequestEditorFn) (*TektonResultsGetTaskRunLogsResponse, error)
}

type ConfigGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		ClusterName           string `json:"clusterName"`
		DefaultNamespace      string `json:"defaultNamespace"`
		DependencyTrackWebUrl string `json:"dependencyTrackWebUrl"`
		SonarWebUrl           string `json:"sonarWebUrl"`
	}
	JSON401 *ErrorUNAUTHORIZED
	JSON403 *ErrorFORBIDDEN
	JSON500 *ErrorINTERNALSERVERERROR
}

// Status returns HTTPResponse.Status
func (r ConfigGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConfigGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ConfigOidcResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		OidcIssuerUrl string `json:"oidcIssuerUrl"`
	}
	JSON500 *ErrorINTERNALSERVERERROR
}

// Status returns HTTPResponse.Status
func (r ConfigOidcResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConfigOidcResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TektonResultsGetPipelineRunResultsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PipelineRunResultsResponse
	JSON400      *ErrorBADREQUEST
	JSON401      *ErrorUNAUTHORIZED
	JSON403      *ErrorFORBIDDEN
	JSON404      *ErrorNOTFOUND
	JSON500      *ErrorINTERNALSERVERERROR
}

// Status returns HTTPResponse.Status
func (r TektonResultsGetPipelineRunResultsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TektonResultsGetPipelineRunResultsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TektonResultsGetPipelineRunLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Logs string `json:"logs"`
	}
	JSON400 *ErrorBADREQUEST
	JSON401 *ErrorUNAUTHORIZED
	JSON403 *ErrorFORBIDDEN
	JSON404 *ErrorNOTFOUND
	JSON500 *ErrorINTERNALSERVERERROR
}

// Status returns HTTPResponse.Status
func (r TektonResultsGetPipelineRunLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TektonResultsGetPipelineRunLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TektonResultsGetTaskRunRecordsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TaskRunRecordsResponse
	JSON400      *ErrorBADREQUEST
	JSON401      *ErrorUNAUTHORIZED
	JSON403      *ErrorFORBIDDEN
	JSON404      *ErrorNOTFOUND
	JSON500      *ErrorINTERNALSERVERERROR
}

// Status returns HTTPResponse.Status
func (r TektonResultsGetTaskRunRecordsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TektonResultsGetTaskRunRecordsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type K8sGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		ApiVersion           string                  `json:"apiVersion"`
		Kind                 string                  `json:"kind"`
		Metadata             K8sGet_200_Metadata     `json:"metadata"`
		Spec                 *map[string]interface{} `json:"spec,omitempty"`
		Status               *map[string]interface{} `json:"status,omitempty"`
		AdditionalProperties map[string]interface{}  `json:"-"`
	}
	JSON400 *ErrorBADREQUEST
	JSON401 *ErrorUNAUTHORIZED
	JSON403 *ErrorFORBIDDEN
	JSON500 *ErrorINTERNALSERVERERROR
}
type K8sGet_200_Metadata struct {
	Name                 string                 `json:"name"`
	Namespace            *string                `json:"namespace,omitempty"`
	ResourceVersion      *string                `json:"resourceVersion,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Status returns HTTPResponse.Status
func (r K8sGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r K8sGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type K8sListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		ApiVersion string                   `json:"apiVersion"`
		Items      []K8sList_200_Items_Item `json:"items"`
		Kind       string                   `json:"kind"`
		Metadata   map[string]interface{}   `json:"metadata"`
	}
	JSON400 *ErrorBADREQUEST
	JSON401 *ErrorUNAUTHORIZED
	JSON403 *ErrorFORBIDDEN
	JSON500 *ErrorINTERNALSERVERERROR
}
type K8sList_200_Items_Metadata struct {
	Name                 string                 `json:"name"`
	Namespace            *string                `json:"namespace,omitempty"`
	ResourceVersion      *string                `json:"resourceVersion,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}
type K8sList_200_Items_Item struct {
	ApiVersion           *string                    `json:"apiVersion,omitempty"`
	Kind                 *string                    `json:"kind,omitempty"`
	Metadata             K8sList_200_Items_Metadata `json:"metadata"`
	Spec                 *map[string]interface{}    `json:"spec,omitempty"`
	Status               *map[string]interface{}    `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}     `json:"-"`
}

// Status returns HTTPResponse.Status
func (r K8sListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r K8sListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TektonResultsGetTaskRunLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Error        nullable.Nullable[string] `json:"error"`
		HasLogs      bool                      `json:"hasLogs"`
		Logs         string                    `json:"logs"`
		StepFiltered *bool                     `json:"stepFiltered,omitempty"`
		TaskName     string                    `json:"taskName"`
		TaskRunName  string                    `json:"taskRunName"`
	}
	JSON400 *ErrorBADREQUEST
	JSON401 *ErrorUNAUTHORIZED
	JSON403 *ErrorFORBIDDEN
	JSON404 *ErrorNOTFOUND
	JSON500 *ErrorINTERNALSERVERERROR
}

// Status returns HTTPResponse.Status
func (r TektonResultsGetTaskRunLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TektonResultsGetTaskRunLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ConfigGetWithResponse request returning *ConfigGetResponse
func (c *ClientWithResponses) ConfigGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ConfigGetResponse, error) {
	rsp, err := c.ConfigGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConfigGetResponse(rsp)
}

// ConfigOidcWithResponse request returning *ConfigOidcResponse
func (c *ClientWithResponses) ConfigOidcWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ConfigOidcResponse, error) {
	rsp, err := c.ConfigOidc(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConfigOidcResponse(rsp)
}

// TektonResultsGetPipelineRunResultsWithResponse request returning *TektonResultsGetPipelineRunResultsResponse
func (c *ClientWithResponses) TektonResultsGetPipelineRunResultsWithResponse(ctx context.Context, params *TektonResultsGetPipelineRunResultsParams, reqEditors ...RequestEditorFn) (*TektonResultsGetPipelineRunResultsResponse, error) {
	rsp, err := c.TektonResultsGetPipelineRunResults(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTektonResultsGetPipelineRunResultsResponse(rsp)
}

// TektonResultsGetPipelineRunLogsWithResponse request returning *TektonResultsGetPipelineRunLogsResponse
func (c *ClientWithResponses) TektonResultsGetPipelineRunLogsWithResponse(ctx context.Context, resultUid openapi_types.UUID, params *TektonResultsGetPipelineRunLogsParams, reqEditors ...RequestEditorFn) (*TektonResultsGetPipelineRunLogsResponse, error) {
	rsp, err := c.TektonResultsGetPipelineRunLogs(ctx, resultUid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTektonResultsGetPipelineRunLogsResponse(rsp)
}

// TektonResultsGetTaskRunRecordsWithResponse request returning *TektonResultsGetTaskRunRecordsResponse
func (c *ClientWithResponses) TektonResultsGetTaskRunRecordsWithResponse(ctx context.Context, resultUid openapi_types.UUID, params *TektonResultsGetTaskRunRecordsParams, reqEditors ...RequestEditorFn) (*TektonResultsGetTaskRunRecordsResponse, error) {
	rsp, err := c.TektonResultsGetTaskRunRecords(ctx, resultUid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTektonResultsGetTaskRunRecordsResponse(rsp)
}

// K8sGetWithBodyWithResponse request with arbitrary body returning *K8sGetResponse
func (c *ClientWithResponses) K8sGetWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*K8sGetResponse, error) {
	rsp, err := c.K8sGetWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseK8sGetResponse(rsp)
}

func (c *ClientWithResponses) K8sGetWithResponse(ctx context.Context, body K8sGetJSONRequestBody, reqEditors ...RequestEditorFn) (*K8sGetResponse, error) {
	rsp, err := c.K8sGet(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseK8sGetResponse(rsp)
}

// K8sListWithBodyWithResponse request with arbitrary body returning *K8sListResponse
func (c *ClientWithResponses) K8sListWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*K8sListResponse, error) {
	rsp, err := c.K8sListWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseK8sListResponse(rsp)
}

func (c *ClientWithResponses) K8sListWithResponse(ctx context.Context, body K8sListJSONRequestBody, reqEditors ...RequestEditorFn) (*K8sListResponse, error) {
	rsp, err := c.K8sList(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseK8sListResponse(rsp)
}

// TektonResultsGetTaskRunLogsWithResponse request returning *TektonResultsGetTaskRunLogsResponse
func (c *ClientWithResponses) TektonResultsGetTaskRunLogsWithResponse(ctx context.Context, resultUid openapi_types.UUID, params *TektonResultsGetTaskRunLogsParams, reqEditors ...RequestEditorFn) (*TektonResultsGetTaskRunLogsResponse, error) {
	rsp, err := c.TektonResultsGetTaskRunLogs(ctx, resultUid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTektonResultsGetTaskRunLogsResponse(rsp)
}

// ParseConfigGetResponse parses an HTTP response from a ConfigGetWithResponse call
func ParseConfigGetResponse(rsp *http.Response) (*ConfigGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConfigGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			ClusterName           string `json:"clusterName"`
			DefaultNamespace      string `json:"defaultNamespace"`
			DependencyTrackWebUrl string `json:"dependencyTrackWebUrl"`
			SonarWebUrl           string `json:"sonarWebUrl"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorUNAUTHORIZED
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorFORBIDDEN
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorINTERNALSERVERERROR
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseConfigOidcResponse parses an HTTP response from a ConfigOidcWithResponse call
func ParseConfigOidcResponse(rsp *http.Response) (*ConfigOidcResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConfigOidcResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			OidcIssuerUrl string `json:"oidcIssuerUrl"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorINTERNALSERVERERROR
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseTektonResultsGetPipelineRunResultsResponse parses an HTTP response from a TektonResultsGetPipelineRunResultsWithResponse call
func ParseTektonResultsGetPipelineRunResultsResponse(rsp *http.Response) (*TektonResultsGetPipelineRunResultsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TektonResultsGetPipelineRunResultsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PipelineRunResultsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBADREQUEST
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorUNAUTHORIZED
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorFORBIDDEN
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorNOTFOUND
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorINTERNALSERVERERROR
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseTektonResultsGetPipelineRunLogsResponse parses an HTTP response from a TektonResultsGetPipelineRunLogsWithResponse call
func ParseTektonResultsGetPipelineRunLogsResponse(rsp *http.Response) (*TektonResultsGetPipelineRunLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TektonResultsGetPipelineRunLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Logs string `json:"logs"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBADREQUEST
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorUNAUTHORIZED
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorFORBIDDEN
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorNOTFOUND
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorINTERNALSERVERERROR
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseTektonResultsGetTaskRunRecordsResponse parses an HTTP response from a TektonResultsGetTaskRunRecordsWithResponse call
func ParseTektonResultsGetTaskRunRecordsResponse(rsp *http.Response) (*TektonResultsGetTaskRunRecordsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TektonResultsGetTaskRunRecordsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TaskRunRecordsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBADREQUEST
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorUNAUTHORIZED
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorFORBIDDEN
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorNOTFOUND
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorINTERNALSERVERERROR
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseK8sGetResponse parses an HTTP response from a K8sGetWithResponse call
func ParseK8sGetResponse(rsp *http.Response) (*K8sGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &K8sGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			ApiVersion           string                  `json:"apiVersion"`
			Kind                 string                  `json:"kind"`
			Metadata             K8sGet_200_Metadata     `json:"metadata"`
			Spec                 *map[string]interface{} `json:"spec,omitempty"`
			Status               *map[string]interface{} `json:"status,omitempty"`
			AdditionalProperties map[string]interface{}  `json:"-"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBADREQUEST
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorUNAUTHORIZED
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorFORBIDDEN
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorINTERNALSERVERERROR
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseK8sListResponse parses an HTTP response from a K8sListWithResponse call
func ParseK8sListResponse(rsp *http.Response) (*K8sListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &K8sListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			ApiVersion string                   `json:"apiVersion"`
			Items      []K8sList_200_Items_Item `json:"items"`
			Kind       string                   `json:"kind"`
			Metadata   map[string]interface{}   `json:"metadata"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBADREQUEST
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorUNAUTHORIZED
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorFORBIDDEN
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorINTERNALSERVERERROR
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseTektonResultsGetTaskRunLogsResponse parses an HTTP response from a TektonResultsGetTaskRunLogsWithResponse call
func ParseTektonResultsGetTaskRunLogsResponse(rsp *http.Response) (*TektonResultsGetTaskRunLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TektonResultsGetTaskRunLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Error        nullable.Nullable[string] `json:"error"`
			HasLogs      bool                      `json:"hasLogs"`
			Logs         string                    `json:"logs"`
			StepFiltered *bool                     `json:"stepFiltered,omitempty"`
			TaskName     string                    `json:"taskName"`
			TaskRunName  string                    `json:"taskRunName"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBADREQUEST
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorUNAUTHORIZED
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorFORBIDDEN
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorNOTFOUND
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorINTERNALSERVERERROR
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
